server:
    port: 8008

spring:
    profiles:
        active: dev

---
# use this variable to expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root1234
        url: jdbc:mysql://localhost:3306/ddbb-spring
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: 'Hi from a Demo App! from dev'

---

spring:
    config:
        activate:
            on-profile: qa
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root1234
        url: jdbc:mysql://localhost:3306/ddbb-spring
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: 'Hi from a Demo App! from qa'

---

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root1234
        url: jdbc:mysql://localhost:3306/ddbb-spring
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: 'Hi from a Demo App! from prod'